// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_3Dn83SppP1g41vMZKhhsVnNKtuEnrDo',
    appId: '1:272906049482:web:bf6531a66ecb83eda3e133',
    messagingSenderId: '272906049482',
    projectId: 'marapp-37d35',
    authDomain: 'marapp-37d35.firebaseapp.com',
    storageBucket: 'marapp-37d35.firebasestorage.app',
    measurementId: 'G-Y5H7RBPWFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ9VGIg6hFOJxfD_wI3ttmKUgNniBV6ks',
    appId: '1:272906049482:android:35b33f241567ac3fa3e133',
    messagingSenderId: '272906049482',
    projectId: 'marapp-37d35',
    storageBucket: 'marapp-37d35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Y6ztP3wRPJsnHI-b_3wbEWeO7BcThBQ',
    appId: '1:272906049482:ios:07dd3f212bc42c18a3e133',
    messagingSenderId: '272906049482',
    projectId: 'marapp-37d35',
    storageBucket: 'marapp-37d35.firebasestorage.app',
    iosBundleId: 'com.example.marapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Y6ztP3wRPJsnHI-b_3wbEWeO7BcThBQ',
    appId: '1:272906049482:ios:07dd3f212bc42c18a3e133',
    messagingSenderId: '272906049482',
    projectId: 'marapp-37d35',
    storageBucket: 'marapp-37d35.firebasestorage.app',
    iosBundleId: 'com.example.marapp',
  );
}
