// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe9JJND4gv8UpHsdu95Qmu4To6AKNSe-c',
    appId: '1:776061981443:web:e0e56496e530cd2ee24f36',
    messagingSenderId: '776061981443',
    projectId: 'marapp-38546',
    authDomain: 'marapp-38546.firebaseapp.com',
    storageBucket: 'marapp-38546.firebasestorage.app',
    measurementId: 'G-VNBEGNF3TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBchfymgPESmGSqzg8G2zq4zCLPoqTiA4g',
    appId: '1:776061981443:android:812a59a58c60b8e2e24f36',
    messagingSenderId: '776061981443',
    projectId: 'marapp-38546',
    storageBucket: 'marapp-38546.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLIhBnV-3O3lOUJGp6UsuAwsmwwZj7XnQ',
    appId: '1:776061981443:ios:2d08ee091f7a01bde24f36',
    messagingSenderId: '776061981443',
    projectId: 'marapp-38546',
    storageBucket: 'marapp-38546.firebasestorage.app',
    iosBundleId: 'com.example.marapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLIhBnV-3O3lOUJGp6UsuAwsmwwZj7XnQ',
    appId: '1:776061981443:ios:2d08ee091f7a01bde24f36',
    messagingSenderId: '776061981443',
    projectId: 'marapp-38546',
    storageBucket: 'marapp-38546.firebasestorage.app',
    iosBundleId: 'com.example.marapp',
  );

}