// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macOS;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpqLig0zbavHNfXxOqcUCNtKYwICy29Q',
    appId: '1:645919336241:android:52ed4137f6cd012ff6b210',
    messagingSenderId: '645919336241',
    projectId: 'marapp-2041e',
    storageBucket: 'marapp-2041e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtW9waTd10NtID9TryzMK9CNOh6p1ZOcE',
    appId: '1:645919336241:ios:d671d503b08c147ef6b210',
    messagingSenderId: '645919336241',
    projectId: 'marapp-2041e',
    storageBucket: 'marapp-2041e.appspot.com',
    iosBundleId: 'com.example.marapp',
  );

  static const FirebaseOptions macOS = FirebaseOptions(
    apiKey: 'AIzaSyAtW9waTd10NtID9TryzMK9CNOh6p1ZOcE',
    appId: '1:645919336241:ios:d671d503b08c147ef6b210',
    messagingSenderId: '645919336241',
    projectId: 'marapp-2041e',
    storageBucket: 'marapp-2041e.appspot.com',
    iosBundleId: 'com.example.marapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7wZb2tO1-Fs6GbDADUSTs2Qs3w08Hovw',
    appId: '1:406099696497:web:87e25e51afe982cd3574d0',
    messagingSenderId: '406099696497',
    projectId: 'marapp-2041e',
    storageBucket: 'marapp-2041e.appspot.com',
  );
}
