name: flutter

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 15'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - name: Create .env file
        run: |
          echo "EMAILJS_API_KEY=${{ secrets.EMAILJS_API_KEY }}" > .env
          echo "SERVICE_ID=${{ secrets.SERVICE_ID }}" >> .env
          echo "TEMPLATE_ID=${{ secrets.TEMPLATE_ID }}" >> .env
          echo "imgurAuthToken=${{ secrets.IMGUR_AUTH_TOKEN }}" >> .env
          echo "OpenCageapiKey=${{ secrets.OPENCAGE_API_KEY }}" >> .env
          echo "EMAILJS_PRIVATE_KEY=${{ secrets.EMAILJS_PRIVATE_KEY }}" >> .env

      - run: flutter test
